"""Builds the OpenAPI 3.1 document and the field reference straight from the Pydantic models.

The committed ``openapi.yaml`` and ``docs/veri_sozlesmesi_alanlar.md`` are generated by
``scripts/export_contracts.py``; a test fails when they drift from the models.
"""

from typing import Any

import yaml

from onkos.contracts import SCHEMA_VERSION
from onkos.contracts.schemas import (
    ALL_MODELS,
    DISCLAIMER,
    DrugRecommendation,
    DrugRecommendationRequest,
    ExplainRequest,
    ExplainResponse,
    HealthResponse,
    MutationPrediction,
    MutationPredictionRequest,
    ReportRequest,
    ReportResponse,
    SimulationRequest,
    SimulationResponse,
    VersionedMessage,
)

_REF = "#/components/schemas/{model}"
PROBLEM_JSON = "application/problem+json"

# path -> (operationId, summary, request model, response model)
OPERATIONS: dict[str, tuple[str, str, type[VersionedMessage], type[VersionedMessage]]] = {
    "/predict/mutation": (
        "predictMutation",
        "Gen mutasyon olasılıklarını tahmin et",
        MutationPredictionRequest,
        MutationPrediction,
    ),
    "/recommend/drugs": (
        "recommendDrugs",
        "Mutasyon profiline göre ilaç sırala",
        DrugRecommendationRequest,
        DrugRecommendation,
    ),
    "/report": ("generateReport", "Doktor raporu üret", ReportRequest, ReportResponse),
    "/simulate": (
        "simulateTreatment",
        "Kavramsal tedavi simülasyonu",
        SimulationRequest,
        SimulationResponse,
    ),
    "/explain": ("explainSlide", "Isı haritası ile açıkla", ExplainRequest, ExplainResponse),
}

_ERRORS = {
    "400": "Geçersiz istek",
    "404": "Kaynak bulunamadı",
    "422": "Doğrulama hatası",
    "429": "Çok fazla istek",
    "500": "Sunucu hatası",
    "503": "Model kullanılamıyor",
}


def _ref(name: str) -> dict[str, str]:
    return {"$ref": _REF.format(model=name)}


def build_components() -> dict[str, Any]:
    """JSON schemas of every contract model, with nested ``$defs`` hoisted to components."""
    schemas: dict[str, Any] = {}
    for model in ALL_MODELS:
        schema = model.model_json_schema(ref_template=_REF)
        for name, sub in schema.pop("$defs", {}).items():
            schemas.setdefault(name, sub)
        schemas[model.__name__] = schema
    return dict(sorted(schemas.items()))


def build_openapi() -> dict[str, Any]:
    """Return the full OpenAPI document as a plain dict."""
    problem = {"description": "Hata", "content": {PROBLEM_JSON: {"schema": _ref("ProblemDetails")}}}
    paths: dict[str, Any] = {
        "/health": {
            "get": {
                "operationId": "health",
                "summary": "Servis sağlık kontrolü",
                "responses": {
                    "200": {
                        "description": "Servis ayakta",
                        "content": {"application/json": {"schema": _ref(HealthResponse.__name__)}},
                    }
                },
            }
        }
    }
    for path, (op_id, summary, request, response) in OPERATIONS.items():
        responses: dict[str, Any] = {
            "200": {
                "description": "Başarılı",
                "content": {"application/json": {"schema": _ref(response.__name__)}},
            }
        }
        for status, text in _ERRORS.items():
            responses[status] = {**problem, "description": text}
        paths[path] = {
            "post": {
                "operationId": op_id,
                "summary": summary,
                "requestBody": {
                    "required": True,
                    "content": {"application/json": {"schema": _ref(request.__name__)}},
                },
                "responses": responses,
            }
        }
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "ONKOS API",
            "version": SCHEMA_VERSION,
            "description": DISCLAIMER + " Bu belge onkos/contracts/schemas.py'den üretilir; "
            "elle düzenlemeyin (scripts/export_contracts.py).",
        },
        "paths": paths,
        "components": {"schemas": build_components()},
    }


def openapi_yaml() -> str:
    return yaml.safe_dump(build_openapi(), sort_keys=False, allow_unicode=True, width=100)


# ------------------------------------------------------------------ field reference (Markdown)
def _type_of(prop: dict[str, Any]) -> str:
    if "$ref" in prop:
        return str(prop["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in prop:
        return " | ".join(_type_of(p) for p in prop["anyOf"])
    if "const" in prop:
        return f"const {prop['const']}"
    if prop.get("type") == "array":
        return f"list[{_type_of(prop.get('items', {}))}]"
    if "enum" in prop:
        return "enum(" + ", ".join(str(v) for v in prop["enum"]) + ")"
    return str(prop.get("type", "any"))


def _constraints(prop: dict[str, Any]) -> str:
    keys = ("minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "minLength", "maxLength")
    parts = [f"{k}={prop[k]}" for k in keys + ("minItems", "maxItems") if k in prop]
    if "pattern" in prop:
        parts.append(f"pattern=`{prop['pattern']}`")
    if "default" in prop:
        parts.append(f"default={prop['default']!r}")
    return "; ".join(parts)


def field_reference_markdown() -> str:
    """Markdown tables: every field's type, requiredness, constraints, meaning."""
    lines = [
        "# Veri Sözleşmesi: Alan Referansı",
        "",
        f"> Sürüm {SCHEMA_VERSION}. Bu dosya `scripts/export_contracts.py` ile "
        "`onkos/contracts/schemas.py`'den üretilir; elle düzenlemeyin.",
        "",
    ]
    for name, schema in build_components().items():
        required = set(schema.get("required", []))
        lines += [f"## {name}", ""]
        if schema.get("description"):
            lines += [str(schema["description"]).strip().split("\n")[0], ""]
        lines += ["| Alan | Tür | Zorunlu | Kısıtlar | Anlam |", "|---|---|---|---|---|"]
        for field, prop in schema.get("properties", {}).items():
            desc = str(prop.get("description", "")).replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| `{field}` | {_type_of(prop)} | {'evet' if field in required else 'hayır'} "
                f"| {_constraints(prop)} | {desc} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
